name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          version: v1.39

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Download gocov
      run: go get github.com/axw/gocov/gocov
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: gocov test ./... -race -failfast -timeout 1m